### ISSUE TITLE
DigitalOcean managed redis compatibility

### ISSUE THREAD

**Issue by janstoeckler** [racompass/racompass#1]
Hey folks,

i really like the application's feature set & design! The one problem I seem to have is not being able to connect to DigitalOcean managed redis instances (without a multitude of errors). 

Can you elaborate if those managed redis instances are supported and if so, how to correctly connect to them?

Thanks!

**Comment by appsnano** [comment]
Hi @janstoeckler,

Thank you for using our product.

According to [Connect to the Database](https://docs.digitalocean.com/products/databases/redis/how-to/connect/#connect-to-the-database), we figured out the problem, because their managed databases are encrypted with TLS/SSL.
So, to connect DO managed Redis instance with below format:


> - Host: redis-test-do-user-4915853-0.db.ondigitalocean.com
> - Port: 25061
> - Username: (leave it blank)
> - Password: your_password
> - [x] Connect using SSL(without key file, cert, ca cert)

<img width="527" alt="Screenshot 2021-06-05 at 12 49 46" src="https://user-images.githubusercontent.com/43163425/120880338-8fcded00-c5fc-11eb-9908-ea5560c64326.png">

However, we found out another issues, while connecting to DO managed Redis due to some Redis commands disabled or renamed [Ref:disabling-of-specific-commands](https://redis.io/topics/security#disabling-of-specific-commands).

Since Racompass uses Redis commands such as `Config`, `Command`, `INFO`, `CLIENT` ,`ACL` and so on by default in current version, it might prompt unknown command alerts when DO managed Redis connected.

For fixing these issues, a new version will be published asap in the coming days.
